--Script generated by Aqua Data Studio 21.0.4 on Mar-11-2022 11:23:07 AM;
--Database: demodb;
--Schema: <All Schemas>;
--Objects: DATATYPE, SEQUENCE, TABLE, TRIGGER;
CREATE SCHEMA app AUTHORIZATION postgres;
--GO
CREATE SCHEMA security AUTHORIZATION postgres;
--GO
CREATE SEQUENCE "app"."mark_seq" INCREMENT BY 1 NO MINVALUE NO MAXVALUE START WITH 1 CACHE 20 NO CYCLE;
--GO
ALTER SEQUENCE "app"."mark_seq" OWNER TO "postgres";
--GO
CREATE SEQUENCE "security"."role_seq" INCREMENT BY 1 NO MINVALUE MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
--GO
ALTER SEQUENCE "security"."role_seq" OWNER TO "postgres";
--GO
CREATE SEQUENCE "app"."stream_seq" INCREMENT BY 1 NO MINVALUE MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
--GO
ALTER SEQUENCE "app"."stream_seq" OWNER TO "postgres";
--GO
CREATE SEQUENCE "app"."student_mark_seq" INCREMENT BY 1 NO MINVALUE MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
--GO
ALTER SEQUENCE "app"."student_mark_seq" OWNER TO "postgres";
--GO
CREATE SEQUENCE "app"."student_seq" INCREMENT BY 1 NO MINVALUE MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
--GO
ALTER SEQUENCE "app"."student_seq" OWNER TO "postgres";
--GO
CREATE SEQUENCE "app"."subject_seq" INCREMENT BY 1 NO MINVALUE MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
--GO
ALTER SEQUENCE "app"."subject_seq" OWNER TO "postgres";
--GO
CREATE SEQUENCE "security"."user_role_seq" INCREMENT BY 1 NO MINVALUE MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
--GO
ALTER SEQUENCE "security"."user_role_seq" OWNER TO "postgres";
--GO
CREATE SEQUENCE "security"."user_seq" INCREMENT BY 1 NO MINVALUE MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE;
--GO
ALTER SEQUENCE "security"."user_seq" OWNER TO "postgres";
--GO
CREATE TABLE "app"."grade" ( "grade_id" bigint NOT NULL, "grade_name" varchar(20) NOT NULL, "grade_code" varchar(20) NOT NULL, PRIMARY KEY("grade_id") );
--GO
ALTER TABLE "app"."grade" OWNER TO "postgres";
--GO
CREATE TABLE "app"."mark" ( "mark_id" bigint NOT NULL, "total_mark" double precision NULL, "student_mark" bigint NULL, "assessment_type" varchar(250) NULL, "assessment_name" varchar(250) NULL, PRIMARY KEY("mark_id") );
--GO
ALTER TABLE "app"."mark" OWNER TO "postgres";
--GO
CREATE TABLE "security"."role" ( "role_id" bigint NOT NULL, "role_name" varchar(40) NULL, PRIMARY KEY("role_id") );
--GO
ALTER TABLE "security"."role" OWNER TO "postgres";
--GO
CREATE TABLE "app"."stream" ( "stream_id" bigint NOT NULL, "stream_name" varchar NOT NULL, "stream_code" varchar NULL, PRIMARY KEY("stream_id") );
--GO
ALTER TABLE "app"."stream" OWNER TO "postgres";
--GO
CREATE TABLE "app"."student" ( "student_id" bigint NOT NULL, "active" boolean NULL DEFAULT true, "registration_date" date NULL, "user_id" bigint NOT NULL, "grade_id" bigint NOT NULL, PRIMARY KEY("student_id") );
--GO
ALTER TABLE "app"."student" OWNER TO "postgres";
--GO
CREATE TABLE "app"."student_mark" ( "student_mark__id" bigint NOT NULL, "subject_id" bigint NULL, "student_id" bigint NULL, "mark_id" bigint NULL, PRIMARY KEY("student_mark__id") );
--GO
ALTER TABLE "app"."student_mark" OWNER TO "postgres";
--GO
CREATE TABLE "app"."subject" ( "subject_id" bigint NOT NULL, "subject_name" varchar(80) NOT NULL, "subject_code" varchar(15) NULL, "stream_id" bigint NOT NULL, PRIMARY KEY("subject_id") );
--GO
ALTER TABLE "app"."subject" OWNER TO "postgres";
--GO
CREATE TABLE "security"."user_role" ( "user_role_id" bigint NOT NULL, "user_id" bigint NULL, "role_id" bigint NULL, PRIMARY KEY("user_role_id") );
--GO
ALTER TABLE "security"."user_role" OWNER TO "postgres";
--GO
CREATE TABLE "security"."users" ( "user_id" bigint NOT NULL, "firstname" varchar(250) NULL, "lastname" varchar(250) NULL, "email" varchar(80) NULL, "phonenumber" varchar(10) NULL, "username" varchar(25) NULL, "password" varchar(250) NULL, "enabled" boolean NULL DEFAULT true, PRIMARY KEY("user_id") );
--GO
ALTER TABLE "security"."users" OWNER TO "postgres";
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 1, 'Grade 1', 'GR1' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 2, 'Grade 2', 'GR2' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 3, 'Grade 3', 'GR3' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 4, 'Grade 4', 'GR4' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 5, 'Grade 5', 'GR5' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 6, 'Grade 6', 'GR6' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 7, 'Grade 7', 'GR7' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 8, 'Grade 8', 'GR8' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 9, 'Grade 9', 'GR9' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 10, 'Grade 10', 'GR10' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 11, 'Grade 11', 'GR11' );
--GO
INSERT INTO "app"."grade"("grade_id", "grade_name", "grade_code") VALUES ( 12, 'Grade 12', 'GR12' );
--GO
INSERT INTO "security"."role"("role_id", "role_name") VALUES ( nextval('security.role_seq'), 'admin_authorization' );
--GO
INSERT INTO "security"."role"("role_id", "role_name") VALUES ( nextval('security.role_seq'), 'teacher_authorization' );
--GO
INSERT INTO "security"."role"("role_id", "role_name") VALUES ( nextval('security.role_seq'), 'student_authorization' );
--GO
INSERT INTO "app"."stream"("stream_id", "stream_name", "stream_code") VALUES ( nextval('app.stream_seq'), 'MATHS & SCIENCE', 'SCI' );
--GO
INSERT INTO "app"."stream"("stream_id", "stream_name", "stream_code") VALUES ( nextval('app.stream_seq'), 'ACCOUNTING', 'ACC' );
--GO
INSERT INTO "app"."stream"("stream_id", "stream_name", "stream_code") VALUES ( nextval('app.stream_seq'), 'GENERAL', 'GEN' );
--GO
INSERT INTO "app"."stream"("stream_id", "stream_name", "stream_code") VALUES ( nextval('app.stream_seq'), 'ALL', 'ALL' );
--GO
INSERT INTO "app"."student"("student_id", "active", "registration_date", "user_id", "grade_id") VALUES ( nextval('app.student_seq'), true, '2022-03-10', 2, 8 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'MATHEMATICS', 'MAT01', 1 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'PHYSICAL SCIENCES', 'PHSYCS', 1 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'LIFE SCIENCES', 'LFSCS', 1 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'GEOGRAPHY', 'GEO', 1 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'BUSINESS MANAGEMENT', 'BUSMG', 2 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ACCOUNTING', 'ACC', 2 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'HISTORY', 'HSTRY', 3 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ECONOMIC MANAGEMENT SYSTEM', 'EMS', 3 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ART & CULTURE', 'ART', 3 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ISIZULU HL', 'ZULHL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ISIZULU SL', 'ZULFAL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ISIXHOSA HL', 'XHOSAHL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ISIXHOSA FAL', 'XHOSAFAL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'SESOTHO HL', 'SOTHOHL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'SESOTHO FAL', 'SOTHOFAL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'XITSONGA HL', 'TSONGHL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'XITSONGA FAL', 'TSONGFAL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ENGLISH HL', 'ENGHL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'ENGLISH FAL', 'ENGFAL', 4 );
--GO
INSERT INTO "app"."subject"("subject_id", "subject_name", "subject_code", "stream_id") VALUES ( nextval('app.subject_seq'), 'LIFE ORIENTATION', 'LO', 4 );
--GO
INSERT INTO "security"."users"("user_id", "firstname", "lastname", "email", "phonenumber", "username", "password", "enabled") VALUES (nextval('security.user_seq'), 'Teacher1', 'Teacher1', 'teacher1@gmail.com', '0812727361', 'teacher1', 'dummy', true );
--GO
INSERT INTO "security"."users"("user_id", "firstname", "lastname", "email", "phonenumber", "username", "password", "enabled") VALUES (nextval('security.user_seq'), 'Student1', 'Lastname1', 'student1@gmail.com', '0812727361', 'student1', 'dummy', true );
--GO
INSERT INTO "security"."users"("user_id", "firstname", "lastname", "email", "phonenumber", "username", "password", "enabled") VALUES (nextval('security.user_seq'), 'System', 'Admin', 'sysadmin@gmail.com', '0812727361', 'admin', 'dummy', true );
--GO
ALTER TABLE "app"."student" ADD CONSTRAINT "user_id_fkey" FOREIGN KEY("user_id") REFERENCES "security"."users"("user_id") MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
ALTER TABLE "app"."student" ADD CONSTRAINT "grade" FOREIGN KEY("grade_id") REFERENCES "app"."grade"("grade_id") MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
ALTER TABLE "app"."student_mark" ADD CONSTRAINT "subject_id_fkey" FOREIGN KEY("subject_id") REFERENCES "app"."subject"("subject_id") MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
ALTER TABLE "app"."student_mark" ADD CONSTRAINT "mark_id_fkey" FOREIGN KEY("mark_id") REFERENCES "app"."mark"("mark_id") MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
ALTER TABLE "app"."subject" ADD CONSTRAINT "subject_stream_fkey" FOREIGN KEY("stream_id") REFERENCES "app"."stream"("stream_id") MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
ALTER TABLE "security"."user_role" ADD CONSTRAINT "users" FOREIGN KEY("user_id") REFERENCES "security"."users"("user_id") MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
ALTER TABLE "security"."user_role" ADD CONSTRAINT "role_id_fkey" FOREIGN KEY("role_id") REFERENCES "security"."role"("role_id") MATCH SIMPLE ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO